# Generated by Django 6.0.1 on 2026-02-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Прайс', max_length=200, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Уникальный URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страница цен',
                'verbose_name_plural': 'Страницы цен',
            },
        ),
        migrations.CreateModel(
            name='PlacementAndLedPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_100k', models.PositiveIntegerField(default=0, help_text='Размещение на обратной стороне билета: тираж 100 000 (сом)', verbose_name='Билеты 100 000')),
                ('ticket_500k', models.PositiveIntegerField(default=0, help_text='Размещение на обратной стороне билета: тираж 500 000 (сом)', verbose_name='Билеты 500 000')),
                ('discount_cards_5000', models.PositiveIntegerField(default=0, help_text='Размещение на дисконтных картах: 5 000 карт (сом)', verbose_name='Дисконтные карты 5 000')),
                ('led_cash_week', models.PositiveIntegerField(default=0, help_text='LED экраны: Касса — 2 LED экрана, цена за НЕДЕЛЮ (сом)', verbose_name='Касса (2 LED) — неделя')),
                ('led_cash_month', models.PositiveIntegerField(default=0, help_text='LED экраны: Касса — 2 LED экрана, цена за МЕСЯЦ (сом)', verbose_name='Касса (2 LED) — месяц')),
                ('led_bar_week', models.PositiveIntegerField(default=0, help_text='LED экраны: Кино Бар — 2 LED экрана, цена за НЕДЕЛЮ (сом)', verbose_name='Кино Бар (2 LED) — неделя')),
                ('led_bar_month', models.PositiveIntegerField(default=0, help_text='LED экраны: Кино Бар — 2 LED экрана, цена за МЕСЯЦ (сом)', verbose_name='Кино Бар (2 LED) — месяц')),
                ('led_inside_week', models.PositiveIntegerField(default=0, help_text='LED экраны: Внутри кинотеатра — 5 LED экранов, цена за НЕДЕЛЮ (сом)', verbose_name='Внутри (5 LED) — неделя')),
                ('led_inside_month', models.PositiveIntegerField(default=0, help_text='LED экраны: Внутри кинотеатра — 5 LED экранов, цена за МЕСЯЦ (сом)', verbose_name='Внутри (5 LED) — месяц')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_led', to='settings.pricepage')),
            ],
            options={
                'verbose_name': 'Билеты/карты/LED цены',
                'verbose_name_plural': 'Билеты/карты/LED цены',
            },
        ),
        migrations.CreateModel(
            name='HallsWeekMonthPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall1_week', models.PositiveIntegerField(default=0, help_text='Зал 1 (Mega): стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 1 — неделя')),
                ('hall1_month', models.PositiveIntegerField(default=0, help_text='Зал 1 (Mega): стоимость за МЕСЯЦ, сом', verbose_name='Зал 1 — месяц')),
                ('hall2_week', models.PositiveIntegerField(default=0, help_text="Let's Go: стоимость за НЕДЕЛЮ, сом", verbose_name='Зал 2 — неделя')),
                ('hall2_month', models.PositiveIntegerField(default=0, help_text="Let's Go: стоимость за МЕСЯЦ, сом", verbose_name='Зал 2 — месяц')),
                ('hall3_week', models.PositiveIntegerField(default=0, help_text='Малый зал (№3): стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 3 — неделя')),
                ('hall3_month', models.PositiveIntegerField(default=0, help_text='Малый зал (№3): стоимость за МЕСЯЦ, сом', verbose_name='Зал 3 — месяц')),
                ('hall4_week', models.PositiveIntegerField(default=0, help_text='Малый зал (№4): стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 4 — неделя')),
                ('hall4_month', models.PositiveIntegerField(default=0, help_text='Малый зал (№4): стоимость за МЕСЯЦ, сом', verbose_name='Зал 4 — месяц')),
                ('hall5_week', models.PositiveIntegerField(default=0, help_text='Малый зал (№5): стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 5 — неделя')),
                ('hall5_month', models.PositiveIntegerField(default=0, help_text='Малый зал (№5): стоимость за МЕСЯЦ, сом', verbose_name='Зал 5 — месяц')),
                ('hall6_week', models.PositiveIntegerField(default=0, help_text='Малый зал (№6): стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 6 — неделя')),
                ('hall6_month', models.PositiveIntegerField(default=0, help_text='Малый зал (№6): стоимость за МЕСЯЦ, сом', verbose_name='Зал 6 — месяц')),
                ('hall7_week', models.PositiveIntegerField(default=0, help_text='VIP зал: стоимость за НЕДЕЛЮ, сом', verbose_name='Зал 7 — неделя')),
                ('hall7_month', models.PositiveIntegerField(default=0, help_text='VIP зал: стоимость за МЕСЯЦ, сом', verbose_name='Зал 7 — месяц')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='halls_week_month', to='settings.pricepage')),
            ],
            options={
                'verbose_name': 'Цены по залам (неделя/месяц)',
                'verbose_name_plural': 'Цены по залам (неделя/месяц)',
            },
        ),
        migrations.CreateModel(
            name='HallsSinglePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall1', models.PositiveIntegerField(default=0, help_text='Зал 1 (Mega): разовая стоимость (сом)', verbose_name='Зал 1')),
                ('hall2', models.PositiveIntegerField(default=0, help_text="Let's Go: разовая стоимость (сом)", verbose_name='Зал 2')),
                ('hall3', models.PositiveIntegerField(default=0, help_text='Малый зал (№3): разовая стоимость (сом)', verbose_name='Зал 3')),
                ('hall4', models.PositiveIntegerField(default=0, help_text='Малый зал (№4): разовая стоимость (сом)', verbose_name='Зал 4')),
                ('hall5', models.PositiveIntegerField(default=0, help_text='Малый зал (№5): разовая стоимость (сом)', verbose_name='Зал 5')),
                ('hall6', models.PositiveIntegerField(default=0, help_text='Малый зал (№6): разовая стоимость (сом)', verbose_name='Зал 6')),
                ('hall7', models.PositiveIntegerField(default=0, help_text='VIP зал: разовая стоимость (сом)', verbose_name='Зал 7')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='halls_single', to='settings.pricepage')),
            ],
            options={
                'verbose_name': 'Цены по залам (разовая)',
                'verbose_name_plural': 'Цены по залам (разовая)',
            },
        ),
        migrations.CreateModel(
            name='BannerAreaMonthlyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_left_month', models.PositiveIntegerField(default=0, help_text='Площадь 6м x 6.7м: стоимость за МЕСЯЦ (сом)', verbose_name='Левый баннер — месяц')),
                ('area_top_month', models.PositiveIntegerField(default=0, help_text='Площадь 5.5м x 4.3м: стоимость за МЕСЯЦ (сом)', verbose_name='Верхний баннер — месяц')),
                ('area_bottom_month', models.PositiveIntegerField(default=0, help_text='Площадь 18м x 5.2м: стоимость за МЕСЯЦ (сом)', verbose_name='Нижний баннер — месяц')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner_areas', to='settings.pricepage')),
            ],
            options={
                'verbose_name': 'Цены по площади (месяц)',
                'verbose_name_plural': 'Цены по площади (месяц)',
            },
        ),
    ]
